---
kind: pipeline
type: docker
name: build-node-14

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - NODE_VERSION=14
      tags:
        - 14

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: build-node-16

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - NODE_VERSION=16
      tags:
        - 16

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: build-node-18

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - NODE_VERSION=18
      tags:
        - 18

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: build-node-20

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - NODE_VERSION=20
      tags:
        - 20

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: build-node-22

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - NODE_VERSION=22
      tags:
        - 22

trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
type: docker
name: build-node-24

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.io
      repo: boro/nodejs
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - NODE_VERSION=24
      tags:
        - 24

trigger:
  branch:
    - main
  event:
    - push
